/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package newpackage;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class showbooks1 extends javax.swing.JPanel {

    /**
     * Creates new form showbooks1
     * @param ans
     */
    
    public showbooks1(int ans) {
        initComponents();
      // JOptionPane.showMessageDialog(this, "hello");
      
        DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
        if(ans==2)
        {String os[]={"saiji","hel","saasd","hsgghd","gst"};
           tblmodel.addRow(os);
            jLabel1.setText("ALL BOOKS OF LIBRARY");
              
        }
        else if(ans==3)
        {
            jLabel1.setText("AVAILABLE BOOKS OF LIBRARY");
            
        }
        else if(ans==4)
        {
            jLabel1.setText("ALL ISSUED BOOKS OF LIBRARY");
            
        }
        

   }
    public showbooks1() {
        initComponents();
    }

    
    showbooks1(int ans, ArrayList<Book> detail) {
         initComponents();
      // JOptionPane.showMessageDialog(this, "hello");
      
        DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
        if(ans==2)
        {
         for(Book j:detail)
           {
               String s[]={j.id,j.title,j.author,j.publishYear,j.status};
               tblmodel.addRow(s);
           }
            jLabel1.setText("ALL BOOKS OF LIBRARY");
              
        }
        else if(ans==3)
        {
            jLabel1.setText("AVAILABLE BOOKS OF LIBRARY");
            for(Book j:detail)
           { if(j.status=="Available")
           {
               String s[]={j.id,j.title,j.author,j.publishYear,j.status};
               tblmodel.addRow(s);
           }
           }
            
        }
        else if(ans==4)
        {
            jLabel1.setText("ALL ISSUED BOOKS OF LIBRARY");
             for(Book j:detail)
           { if(j.status=="Unavailable")
           {
               String s[]={j.id,j.title,j.author,j.publishYear,j.status};
               tblmodel.addRow(s);
           }
           }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Itzikgur-My-Seven-Books-1.512.png"))); // NOI18N
        jLabel1.setText("LIST OF ALL BOOKS OF LIBRARY");

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "TITLE", "AUTHOR", "PUBLISH YEAR", "STATUS"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
